[2021-07-09 04:36:14,940] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: bluepi_dag.LoadToDataWarehouse.load_users 2021-07-09T04:36:02.713158+00:00 [queued]>
[2021-07-09 04:36:14,954] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: bluepi_dag.LoadToDataWarehouse.load_users 2021-07-09T04:36:02.713158+00:00 [queued]>
[2021-07-09 04:36:14,955] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-09 04:36:14,956] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-09 04:36:14,956] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-09 04:36:14,973] {taskinstance.py:1107} INFO - Executing <Task(GCSToBigQueryOperator): LoadToDataWarehouse.load_users> on 2021-07-09T04:36:02.713158+00:00
[2021-07-09 04:36:14,979] {standard_task_runner.py:52} INFO - Started process 9168 to run task
[2021-07-09 04:36:14,985] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'bluepi_dag', 'LoadToDataWarehouse.load_users', '2021-07-09T04:36:02.713158+00:00', '--job-id', '341', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/bluepi_dag.py', '--cfg-path', '/tmp/tmpst3y7ixc', '--error-file', '/tmp/tmp9nyhak9w']
[2021-07-09 04:36:14,994] {standard_task_runner.py:77} INFO - Job 341: Subtask LoadToDataWarehouse.load_users
[2021-07-09 04:36:15,049] {logging_mixin.py:104} INFO - Running <TaskInstance: bluepi_dag.LoadToDataWarehouse.load_users 2021-07-09T04:36:02.713158+00:00 [running]> on host 3cf0296804bd
[2021-07-09 04:36:15,115] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=natchanon
AIRFLOW_CTX_DAG_ID=bluepi_dag
AIRFLOW_CTX_TASK_ID=LoadToDataWarehouse.load_users
AIRFLOW_CTX_EXECUTION_DATE=2021-07-09T04:36:02.713158+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-09T04:36:02.713158+00:00
[2021-07-09 04:36:15,121] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/***/providers/google/cloud/transfers/gcs_to_bigquery.py:264 DeprecationWarning: The bigquery_conn_id parameter has been deprecated. You should pass the gcp_conn_id parameter.
[2021-07-09 04:36:15,132] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/***/providers/google/cloud/hooks/bigquery.py:142 DeprecationWarning: This method will be deprecated. Please use `BigQueryHook.get_client` method
[2021-07-09 04:36:15,233] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/***/models/taskinstance.py:1361 DeprecationWarning: This method is deprecated. Please use `***.providers.google.cloud.hooks.bigquery.BigQueryHook.run_load`
[2021-07-09 04:36:15,235] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/***/providers/google/cloud/hooks/bigquery.py:1774 DeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
[2021-07-09 04:36:15,236] {bigquery.py:3013} INFO - Project not included in destination_project_dataset_table: bluepi_dataset.users; using project "exam-de-natchanon"
[2021-07-09 04:36:15,237] {bigquery.py:1639} INFO - Inserting job ***_1625805375236735_2545dcb583425e0dd487b957a401eec7
[2021-07-09 04:36:20,436] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=bluepi_dag, task_id=LoadToDataWarehouse.load_users, execution_date=20210709T043602, start_date=20210709T043614, end_date=20210709T043620
[2021-07-09 04:36:20,470] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-09 04:36:20,499] {local_task_job.py:151} INFO - Task exited with return code 0
